# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 889c5938b2b06ad5628d402dbcf456a76f28e8711a7bf6dc97299b351c50de20ba83286173bb3b792389ecb0a9d31abb5b54660a00f3fdc3296eaafa5bc29c4d

test:
  secret_key_base: 932cc45cf188b2a9c526d70d114750cfeb2d80c5b8a1e43f3e42f65426508437e9c016a46bb6860e89f663016f6771b0366bf3895bc0cc347e197e9530e49277

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
